package org.shipkit.internal.notes.about;

import java.io.File;

public class InformationAboutProvider {

    public static final String INFORMATION_ABOUT = "<sup><sup>*This release notes was automatically generated by [shipkit](http://shipkit.org/) %d times.*</sup></sup>\n\n";
    public static final String COMMENT_START = "<!---";
    public static final String COMMENT_END = "--->";

    private final ReleaseNoteCounter releaseNoteCounter = new ReleaseNoteCounter();

    public String getInfoText(File releaseNoteFile, boolean informationAboutEnabled) {
        int nextReleaseNoteNumber = releaseNoteCounter.getNextReleaseNoteNumber(releaseNoteFile);
        String infoAbout = String.format(INFORMATION_ABOUT, nextReleaseNoteNumber);
        return addComment(infoAbout, informationAboutEnabled);
    }

    private String addComment(String informationAbout, Boolean informationAboutEnabled) {
        if (!informationAboutEnabled) {
            return COMMENT_START + informationAbout + COMMENT_END;
        }
        return informationAbout;
    }
}
