package org.shipkit.internal.notes.about;

import java.io.File;

public class InformationAboutProvider {

    public String getInfoText(File releaseNoteFile, boolean informationAboutEnabled){
        return "<sup><sup>This release notes was automatically generated by shipkit X times.</sup></sup>";
    }
}
