package org.shipkit.internal.notes.about

import spock.lang.Specification

class InformationAboutProviderTest extends Specification {

    private final  InformationAboutProvider testObj = new InformationAboutProvider();

    def "when file not exist and infromation about is enabled should return initail value"() {
        given:
        File releaseNoteFile = new File("notExistFile.neg")
        when:
        String result = testObj.getInfoText(releaseNoteFile,true);
        then:
        result == "<sup><sup>This release notes was automatically generated by shipkit 1 times.</sup></sup>"
    }
}
